on:
  issues:
    types:
      - opened
      - reopened

jobs:
  notion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const test = ${{ github.event.issue.assignees }}
            console.log(test);
            console.log("${{ github.event.issue.labels[1].name }}");
