on:
  issues:
    types:
      - opened
      - reopened
      - closed

jobs:
  notion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check notion database
        id: notion
        run: |
          echo '${{ toJSON(github.event.issue.assignees.*.login) }}' > assignees.json
          echo '${{ toJSON(github.event.issue.labels.*.name) }}' > labels.json
          echo '{ "start": "${{ github.event.issue.created_at }}", "end": null, "time_zone": "Asia/Seoul" }' > date.json
          status=""
          assignees=$(cat assignees.json)
          labels=$(cat labels.json)
          
          assignee_result=$(jq '[.[] | { name: . }] | .[]' assignees.json)
          echo "$assignee_result" > assignees.json
          
          label_result=$(jq '[.[] | { name: . }] | .[]' labels.json)
          echo "$label_result" > labels.json
          
          if [ "$status" == "" ]; then
            status="Opened"
          elif [ "2024-12-18T14:46:33Z" != "" ]; then
            status="Closed"
            date=$(jq '.end="2024-12-18T14:46:33Z"' date.json)
            echo "$date" > date.json
          fi
          
          assignees=$(cat assignees.json)
          labels=$(cat labels.json)
          date=$(cat date.json)
          
          echo "status=$status" >> $GITHUB_OUTPUT
          echo "assignees=$(echo "${assignees}" | jq -c .)" >> $GITHUB_OUTPUT
          echo "labels=$(echo "${labels}" | jq -c .)" >> $GITHUB_OUTPUT
          echo "date=$(echo "${date}" | jq -c .)" >> $GITHUB_OUTPUT

      - run: echo "${{ steps.properties.outputs.date.start }}"
