on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        run: |
          test='{ "start": "start", "time_zone": "Asia/Seoul" }'
          test=$(jq '. + { "end": "end" } | ${{ fromJSON(test) }})

          echo "test=$test" >> $GITHUB_OUTPUT

      - run: echo "${{ steps.test.outputs.test }}"
