on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "{}" > data.json

          test=$(jq '. + { name: { first: "kim" } } | . + { color: "blue" }' data.json)
          echo "$test" > data.json

          echo "result=$(cat data.json)"
