on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: test
        run: |
          test='{
            "start": "start",
            "end": "end"
          }'

          echo "test=$test" >> $GITHUB_OUTPUT

      - run: echo "${{ steps.test.outputs.test }}"
